development:
  port: 9306
  min_infix_len: 3
  #config_file: "C:\sphinx\binsphinx.conf"
  #searchd_log_file: C:\sphinx\bin/log/searchd.log"
  #query_log_file: "/usr/local/sphinx/var/log/query.log"
  #pid_file: "/usr/local/sphinx/var/log/searchd.pid"
  #bin_path: "/usr/local/sphinx/bin"
  #searchd_binary_name: "/usr/local/sphinx/bin/searchd"
  #indexer_binary_name: "/usr/local/sphinx/bin/indexer"
  config_file: "C:/sphinx/bin/sphinx.conf"
  searchd_log_file: "C:/sphinx//log/searchd.log"
  query_log_file: "C:/sphinx//log/searchd.query.log"
  pid_file: "C:/sphinx/log/searchd.development.pid"
  bin_path: "C:/sphinx/bin"
  searchd_binary_name: "searchd"
  indexer_binary_name: "indexer"